#!/bin/bash
carton exec ./bin/proteins drakkar_run74 vinland_run74
carton exec ./bin/proteins_xrefs vinland_run74
carton exec ./bin/sequences drakkar_run74 vinland_run74
carton exec ./bin/features drakkar_run74 vinland_run74
carton exec ./bin/methods drakkar_run74 vinland_run74
carton exec ./bin/interactions_hh vinland_run74 data/HH_nextprot.csv
carton exec ./bin/interactions_vh drakkar_run74 vinland_run74
carton exec ./bin/edges vinland_run74
carton exec ./bin/publications drakkar_run74 vinland_run74
carton exec ./bin/descriptions_hh vinland_run74 data/HH_nextprot.csv
carton exec ./bin/descriptions_vh drakkar_run74 vinland_run74
carton exec ./bin/mappings_hh vinland_run74 data/HH_nextprot_mapping.csv
carton exec ./bin/mappings_vh drakkar_run74 vinland_run74
carton exec ./bin/taxonomy drakkar_run74 vinland_run74
